[INFO     2014-09-01 12:38:01,932 bulkloader.py] Logging to bulkloader-log-20140901.123801
[INFO     2014-09-01 12:38:01,932 bulkloader.py] Throttling transfers:
[INFO     2014-09-01 12:38:01,932 bulkloader.py] Bandwidth: 250000 bytes/second
[INFO     2014-09-01 12:38:01,932 bulkloader.py] HTTP connections: 8/second
[INFO     2014-09-01 12:38:01,932 bulkloader.py] Entities inserted/fetched/modified: 20/second
[INFO     2014-09-01 12:38:01,932 bulkloader.py] Batch Size: 10
[INFO     2014-09-01 12:38:01,933 bulkloader.py] Opening database: bulkloader-progress-20140901.123801.sql3
[DEBUG    2014-09-01 12:38:01,938 bulkloader.py] [Thread-1] RestoreThread: started
[DEBUG    2014-09-01 12:38:07,219 bulkloader.py] [Thread-1] RestoreThread: exiting
[DEBUG    2014-09-01 12:38:07,658 bulkloader.py] [Thread-2] RestoreThread: started
[DEBUG    2014-09-01 12:38:07,659 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread: started
[DEBUG    2014-09-01 12:38:07,659 bulkloader.py] Configuring remote_api. url_path = /_ah/remote_api, servername = 127.0.0.1:8000
[DEBUG    2014-09-01 12:38:07,668 bulkloader.py] Bulkloader using app_id: dev~tpbgui
[INFO     2014-09-01 12:38:07,668 bulkloader.py] Connecting to 127.0.0.1:8000/_ah/remote_api
[ERROR    2014-09-01 12:38:17,645 bulkloader.py] Authentication Failed: Incorrect credentials or unsupported authentication type (e.g. OpenId).
