[INFO     2014-09-01 12:28:31,720 bulkloader.py] Logging to bulkloader-log-20140901.122831
[INFO     2014-09-01 12:28:31,720 bulkloader.py] Throttling transfers:
[INFO     2014-09-01 12:28:31,720 bulkloader.py] Bandwidth: 250000 bytes/second
[INFO     2014-09-01 12:28:31,720 bulkloader.py] HTTP connections: 8/second
[INFO     2014-09-01 12:28:31,720 bulkloader.py] Entities inserted/fetched/modified: 20/second
[INFO     2014-09-01 12:28:31,721 bulkloader.py] Batch Size: 10
[INFO     2014-09-01 12:28:31,721 bulkloader.py] Opening database: bulkloader-progress-20140901.122831.sql3
[DEBUG    2014-09-01 12:28:31,728 bulkloader.py] [Thread-1] RestoreThread: started
[DEBUG    2014-09-01 12:28:40,821 bulkloader.py] [Thread-2] RestoreThread: started
[DEBUG    2014-09-01 12:28:40,821 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread: started
[DEBUG    2014-09-01 12:28:40,821 bulkloader.py] Configuring remote_api. url_path = /_ah/remote_api, servername = 127.0.0.1:8000
[DEBUG    2014-09-01 12:28:40,822 bulkloader.py] [Thread-1] RestoreThread: exiting
[DEBUG    2014-09-01 12:28:40,828 bulkloader.py] Bulkloader using app_id: dev~tpbgui
[INFO     2014-09-01 12:28:40,829 bulkloader.py] Connecting to 127.0.0.1:8000/_ah/remote_api
[ERROR    2014-09-01 12:28:46,016 bulkloader.py] Authentication Failed: Incorrect credentials or unsupported authentication type (e.g. OpenId).
